_target_: pytorch_lightning.callbacks.ModelCheckpoint 
monitor: val_loss
mode: min 
save_top_k: 1 
save_weights_only: False 
dirpath: checkpoints/${project.name}_${project.version}
filename: best_checkpoint