_target_: pytorch_lightning.callbacks.ModelCheckpoint 
monitor: val_loss
mode: min 
save_top_k: 1 
save_weights_only: False 
dirpath: ${paths.checkpoint_dir}
filename: best_checkpoint
save_on_train_epoch_end: TrueA