defaults: 
  - optimizer: adamw 
  - callbacks: 
      - early_stopping 
      - model_checkpoint 
  - scheduler: 
      - cosine_annealing
  - datamodule
  - save_model
  - project

hydra: 
  run: 
    dir: outputs/${project.name}_${project.version}