defaults: 
  - _self_
  - optimizer: adamw 
  - callbacks: 
      - early_stopping 
      - model_checkpoint 
  - scheduler: 
      - cosine_annealing
  - datamodule: default
  - save_model: default
  - project: default
  - model: default
  - trainer: default

hydra: 
  run: 
    dir: outputs/${project.name}_${project.version}

seed: 42