max_epochs: 10 
accelerator: cuda
devices: 1 
precision: 16-mixed
gradient_clip_val: 1.0
accumulate_grad_batches: 8
val_check_interval: 0.5
deterministic: true
log_every_n_steps: 10
num_sanity_val_steps: 0