defaults: 
  - _self_
  - model: openai
  - generation: default 
  - prompt: default 
  - data: default

run_name: 'chatgpt-3.5-turbo'

hydra: 
  run: 
    dir: outputs/${run_name}/${prompt.prompt_version}

seed: 10

paths: 
  result_path: outputs/${run_name}/${prompt.prompt_version}