defaults: 
  - _self_
  - model: quantized
  - generation: default 
  - prompt: default 
  - data: default

run_name: 'noushermes-2-llama-13B'

hydra: 
  run: 
    dir: outputs/${run_name}/${prompt.prompt_version}

seed: 10

paths: 
  result_path: outputs/${run_name}/${prompt.prompt_version}