model: 
  d_model: 256
  d_k: 64
  d_v: 64
  n_heads: 4
  n_layers: 2 
  ffn_hidden: 1024
  encoder_dropout: 0.2
  decoder_dropout: 0.2
  max_len: 600

training: 
  batch_size: 64
  epochs: 50
  learning_rate: 1e-4
  print_every: 100
  save_every: 600
  patience: 4

paths: 
  model_dir: './models'
  model_file: 'model.pth'
  train_loss_file: 'train_losses.pt'
  val_loss_file': 'val_losses.pt'