# configs/save_model/to_hf.yaml
model_name: 'pegasus_middle_chunking_v1'
save_dir: huggingface_models
repo_name: rmcnamara4/pegasus-middle-chunking-v1
push_to_hub: true 

hydra:
  output_subdir: null
  run:
    dir: .