train_batch_size: 4
test_batch_size: 8 
chunk_len: 512 
stride: 412
min_len: 256
max_len: 1024
num_workers: 8
prefetch_factor: 2
split_sizes: 
  - 200
  - 50
  - 50
chunking_strategy: 'middle'
num_keep: 6
embedding_model_name: null # 'all-MiniLM-L6-v2'
seed: 156